### ISSUE TITLE
Exception in thread "dirigiste-pool-controller-0"

### ISSUE THREAD

**Issue by alvatar** [ztellman/aleph#219]
An executable compiled with `lein uberjar` produces this output when booting:
```
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:233)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:316)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:377)
        at java.lang.Thread.run(Thread.java:745)
```

The output of java -version is:
```
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-6+deb8u1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

The project.clj includes dependencies to Clojure 1.8, [io.aleph/dirigiste "0.1.3-alpha1"], [manifold "0.1.2"] and [aleph "0.4.1-beta5"]

**Comment by ztellman** [comment]
This should be fixed by targeting `[io.aleph/dirigiste "0.1.3"]`.

**Comment by kenrestivo** [comment]
Still seeing this

```
Exception in thread "dirigiste-pool-controller-0" java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;  
        at io.aleph.dirigiste.Stats$UniformLongReservoirMap.toMap(Stats.java:114)
        at io.aleph.dirigiste.Pool.updateStats(Pool.java:237)
        at io.aleph.dirigiste.Pool.startControlLoop(Pool.java:320)
        at io.aleph.dirigiste.Pool.access$500(Pool.java:8)
        at io.aleph.dirigiste.Pool$1.run(Pool.java:381)
        at java.lang.Thread.run(Thread.java:745)
```
 Tree says:

```clojure
 [aleph "0.4.3"]
   [byte-streams "0.2.2"]
     [primitive-math "0.1.5"]
   [io.netty/netty-all "4.1.9.Final"]
   [manifold "0.1.6"]
     [io.aleph/dirigiste "0.1.5"]
     [riddley "0.1.14"]
   [org.clojure/tools.logging "0.3.1" :exclusions [[org.clojure/clojure]]]
```

**Comment by ztellman** [comment]
I believe my Java installation on my local machine got screwed up, it was supposed to compile using 1.7, but appears to have been compiled using 1.8.  I'll address this moving forward.
